engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: true
ratings:
  paths:
  - src/**
  - "server.js"
exclude_paths:
- spec/**/*
- node_modules
