version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node

permissions:
- object: /home/ec2-user
  owner: ec2-user
  group: ec2-user
  mode: 777
  type:
    - directory
    - file

hooks:
  BeforeInstall:
    - location: deployment/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deployment/install_dependencies.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: deployment/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: deployment/stop_server.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: deployment/validate.sh
      timeout: 300
      runas: ec2-user
